language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install:
- npm install -g hexo
- npm install -g hexo-cli
- npm install
before_script:
- git config --global user.name "nooldey"
- git config --global user.email 'openzws@163.com'
- sed -i'' "s~git@github.com:nooldey/nooldey.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/nooldey/nooldey.github.io.git~" _config.yml
script:
- hexo clean
- hexo g
- hexo d
# after_success:
# - cd public
# - git init
# - git add .
# - git commit -m 'Update from travis"
# - git push -f "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - source
env:
  global:
  - GH_REF: github.com/nooldey/nooldey.github.io.git
  - secure: hIYpDCqLwCXoFkLzMwuAHxMOACjhGPs5l97HNGk6CEppy57prKIrDyzMpbEjOYX7URDffjHUSVwShVMMr2oMH+4SRhhqNLN3Xko+aSaxBhmHKiibx4TSTunkjZfYqXSJUKLBdC2tGhYSUQHYwJVeJXM+yPjM27sFbSWsU15NgBY6MQrr5ZZX2Hyk7FLT8i22bKqmkNuVSnqv9W6StPaYI+0fdwlIHe2R57OhX6etsAYzhs5snoVKl71PQz6U+lSqm2JG8+YA2v26ca8keBCtVwMZ+WHUeJWyHjagS6twd5+AJCIHkTsvJM8cFQuuxa1SKT782ClGuddKPvTQmXJuy1Wcf/M1ShrTWBtqPA/0T5UcNgI6yWOGPN0WHotx1sC5yytHxaEu0wKWYZ8xweHQ+bPbr1nU170+M9kgBaejifAACXyG0xTKwdkVhu9J+sefO21RX+xSl3cnKtbzz8XKFzogqn7PXcAKDlyC/ywp2gowVCkdoaTTnhihSNl62bLltKvJ1FFdfdiKMfQsJCH9TmEC0U0hyocHdtOreD2sHHOv47xvPYZuzsaoyhHBiJ1WyMypfEmJ4rUv6PI774M9mdC1YXUwHPxiPR1i+WGwGImfsly0qAoum8oVjW8CR+r6NBRzHWb1qv94j+gr0XE43baGGqz4rYXvfUmNXbnNVAU=
